name: Herring Cove
author: Herring Cove
baseurl: /herring-cove
description: theme for jekyll
github: http://www.github.com/hjpark83
linkedin: http://www.linkedin.com/in/hyunjoon83
email: hyunjoonpark0803@gmail.com
location: 37.5665°N   126.9780°W
disqus: diqus-username

##Make sure to edit the above fields, especially for disqus.


highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
